spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: inwon.private@gmail.com
    password: pptvxpwqdzmvkroa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    debug: true


  datasource:
    url: jdbc:mysql://localhost:3306/soundbrew_test
    username: root
    password: ehdgns12!@
    driver-class-name: com.mysql.cj.jdbc.Driver

com:
  soundbrew:
    jwt:
      secret: happy2025

maintenance:
  mode: false

public:
  paths:
    - /api/sounds/**
    - /api/me/**
    - /api/admin/**
    - /sounds/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /fonts/**
    - /generateToken
    - /register
    - /api/verification/activation
    - /activation
    - /api/users/**
    - /
    - /files/**
    - /myInfo
    - /api/sample/**